- hosts: all
  become: yes
  gather_facts: yes

  tasks:
    - unarchive:
        src: https://github.com/prometheus/node_exporter/releases/download/v0.16.0/node_exporter-0.16.0.linux-amd64.tar.gz
        dest: /tmp
        remote_src: yes
    - command: mv /tmp/node_exporter-0.16.0.linux-amd64/node_exporter /usr/local/bin/node_exporter
    - copy:
        src: node_exporter.service
        dest: /etc/systemd/system/node_exporter.service
      register: unit_file
    - systemd:
        name: node_exporter
        state: started
        enabled: yes
        daemon_reload: "{{ unit_file is changed }}"

