
- hosts: all
  become: yes
  gather_facts: yes

  tasks:
    - name: Install packages
      apt:
        name: "{{ item }}"
        update_cache: yes
      loop:
        - unzip
        - htop
        - tcpdump
        - dstat
    - name: Create tmp dir
      file:
        path: /tmp/kataribe
        state: directory
    - name: Download kataribe
      unarchive:
        src: https://github.com/matsuu/kataribe/releases/download/v0.3.0/linux_amd64.zip
        dest: /tmp/kataribe
        remote_src: yes
    - name: Copy kataribe bin and setting file
      copy:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        mode: "{{ item.mode | default(omit) }}"
        remote_src: yes
      loop:
        - src: /tmp/kataribe/kataribe
          dest: /usr/local/bin/kataribe
          mode: "u=rwx,g=rx,o=rx"
        - src: /tmp/kataribe/kataribe.toml
          dest: /etc/kataribe.toml

    - name: Create isucon user
      user:
        name: isucon
    - name: Set ssh public key
      authorized_key:
        user: isucon
        key: "{{ lookup('file', 'id_rsa.pub') }}"
    - name: Copy ssh private key
      copy:
        src: id_rsa
        dest: "{{ item.dest }}"
        owner: "{{ item.owner }}"
        group: "{{ item.owner }}"
        mode: 0400
        backup: yes
      loop:
        - owner: isucon
          dest: /home/isucon/.ssh/id_rsa
        - owner: root
          dest: /root/.ssh/id_rsa

    - name: Copy logrotate script
      copy:
        src: lotatelog
        dest: /usr/local/bin/lotatelog
        mode: 0755
